/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.EfectoHoverBoton;
import Modelo.EfectoHoverLabel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.border.Border;

/**
 *
 * @author Luis Huayta
 */
public class VentanaEmpresa extends javax.swing.JDialog {

    /**
     * Creates new form VentanaEmpresaa
     */
    public VentanaEmpresa(javax.swing.JFrame parent,boolean modal) {
        super(parent,modal);
        initComponents();
        setLocationRelativeTo(null);
        
        botonGananciaTotal.setBounds(30, 35, 120, 100);
        botonVentasTotal.setBounds(239, 35, 120, 100);
        labelGanancia.setBounds(0, 15, 180, 20);
        labelVenta.setBounds(240, 15, 120, 20);
        
        addPropiedades(botonGananciaTotal);
        addPropiedades(botonVentasTotal);
        addPropiedades(labelGanancia);
        addPropiedades(labelVenta);
        
        jPanelFondo.add(labelGanancia);
        jPanelFondo.add(labelVenta);
        jPanelFondo.add(botonGananciaTotal);
        jPanelFondo.add(botonVentasTotal);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabelBarra = new javax.swing.JLabel();
        jPanelFondo = new javax.swing.JPanel();
        jTextFieldGanancia = new javax.swing.JTextField();
        jTextFieldVentas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setBorderPainted(false);
        jButton1.setFocusable(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 90, 22));
        jPanel1.add(jLabelBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        jPanelFondo.setBackground(new java.awt.Color(18, 18, 18));
        jPanelFondo.setForeground(new java.awt.Color(18, 18, 18));

        jTextFieldGanancia.setEditable(false);
        jTextFieldGanancia.setBackground(new java.awt.Color(18, 18, 18));
        jTextFieldGanancia.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jTextFieldGanancia.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldGanancia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldGanancia.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldGanancia.setFocusable(false);

        jTextFieldVentas.setEditable(false);
        jTextFieldVentas.setBackground(new java.awt.Color(18, 18, 18));
        jTextFieldVentas.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jTextFieldVentas.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldVentas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldVentas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldVentas.setFocusable(false);

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jTextFieldGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(jTextFieldVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
   
    public JButton botonGananciaTotal = new EfectoHoverBoton();
    public JButton botonVentasTotal = new EfectoHoverBoton();
    public JLabel labelGanancia = new EfectoHoverLabel("GANANCIA TOTAL");
    public JLabel labelVenta = new EfectoHoverLabel("VENTA TOTAL");
    
    private void addPropiedades(JButton boton)
    {
        
        boton.setBackground(new Color(18,18,18));
        boton.setContentAreaFilled(false);
        boton.setFocusable(false);
        boton.setBorderPainted(false);
        
    }
    private void addPropiedades(JLabel label)
    {
        label.setOpaque(false);
         label.setForeground(new Color(255,255,255));
        
        label.setFocusable(false);
        label.setHorizontalAlignment(JLabel.CENTER);
        label.setVerticalAlignment(JLabel.CENTER);
        label.setFont(new Font("Estandar",Font.BOLD,15));
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabelBarra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFondo;
    public javax.swing.JTextField jTextFieldGanancia;
    public javax.swing.JTextField jTextFieldVentas;
    // End of variables declaration//GEN-END:variables
}
