/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.EfectoHoverBoton;
import Modelo.EfectoHoverLabel;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Luis Huayta
 */
public class VentanaProductos extends javax.swing.JDialog {

    /**
     * Creates new form VentanaProductos
     */
    public VentanaProductos(javax.swing.JFrame parent,boolean modal) {
        super(parent,modal);
        initComponents();
        setLocationRelativeTo(null);
         botonGanancia.setBounds(10, 40, 120, 100);
        botonVenta.setBounds(10, 120, 120, 100);
        
        addPropiedades(botonGanancia);
        addPropiedades(botonVenta);
        
               
        
        jPanelFondo.add(botonGanancia);
        jPanelFondo.add(botonVenta);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelFondo = new javax.swing.JPanel();
        jTextFieldGanancia = new javax.swing.JTextField();
        jTextFieldVentas = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setBorderPainted(false);
        jButton1.setFocusable(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 100, 20));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 20));

        jPanelFondo.setBackground(new java.awt.Color(18, 18, 18));

        jTextFieldGanancia.setEditable(false);
        jTextFieldGanancia.setBackground(new java.awt.Color(18, 18, 18));
        jTextFieldGanancia.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jTextFieldGanancia.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldGanancia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldGanancia.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldGanancia.setFocusable(false);

        jTextFieldVentas.setEditable(false);
        jTextFieldVentas.setBackground(new java.awt.Color(18, 18, 18));
        jTextFieldVentas.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jTextFieldVentas.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldVentas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldVentas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldVentas.setFocusable(false);

        jComboBox1.setBackground(new java.awt.Color(18, 18, 18));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setAlignmentX(3.0F);
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox1.setFocusable(false);
        jComboBox1.setOpaque(true);

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jTextFieldGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jTextFieldVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 240, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jButton1MouseExited

    
   private void addPropiedades(JButton boton)
    {
        
        boton.setBackground(new Color(18,18,18));
        boton.setContentAreaFilled(false);
        boton.setFocusable(false);
        boton.setBorderPainted(false);
        
    }
    private void addPropiedades(JLabel label)
    {
        label.setOpaque(false);
         label.setForeground(new Color(255,255,255));
        
        label.setFocusable(false);
        label.setHorizontalAlignment(JLabel.CENTER);
        label.setVerticalAlignment(JLabel.CENTER);
        label.setFont(new Font("Estandar",Font.BOLD,15));
    }
    
    public JButton botonGanancia = new EfectoHoverBoton();
    public  JButton botonVenta = new EfectoHoverBoton();
    public  JLabel labelGanancia = new EfectoHoverLabel("GANANCIA");
    public  JLabel labelVenta = new EfectoHoverLabel("VENTA");

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFondo;
    public javax.swing.JTextField jTextFieldGanancia;
    public javax.swing.JTextField jTextFieldVentas;
    // End of variables declaration//GEN-END:variables
}
