/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.EfectoHoverBoton;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Luis Huayta
 */
public class VistaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdministrador
     */
   
    public VistaAdministrador() {
        
        initComponents();
        setLocationRelativeTo(null);
        mayorGanancia.setBounds(12, 12, 487, 233);
        menorGanancia.setBounds(12, 272, 487, 233);
        mayorVenta.setBounds(655, 12, 495, 233);
        menorVenta.setBounds(655, 272, 495, 233);
        gananciaHoy.setBounds(0,35,190,151);
        ventaHoy.setBounds(0,224,190,151);
        
//          mayorGanancia.setBounds(100,12,400,233);
//          menorGanancia.setBounds(100, 272, 400, 233);
//          mayorVenta.setBounds(627, 12, 400, 233);
//          menorVenta.setBounds(627, 272, 400, 233);
        addPropiedades(mayorVenta);
        addPropiedades(menorVenta);
        addPropiedades(mayorGanancia);
        addPropiedades(menorGanancia);
        addPropiedades(ventaHoy);
        addPropiedades(gananciaHoy);
        
        jPanel4.add(ventaHoy);
        jPanel4.add(gananciaHoy);
        
        jPanel6.add(mayorGanancia);
        jPanel6.add(menorGanancia);
        jPanel6.add(mayorVenta);
        jPanel6.add(menorVenta);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonFoto = new javax.swing.JButton();
        jLabelSegundoApellido = new javax.swing.JLabel();
        jLabelPrimerApellido = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonFactura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaFactura = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButtonAgregar = new javax.swing.JButton();
        jButtonModifica = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jLabeTitulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButtonVentaHoy = new javax.swing.JButton();
        jButtonGananciaHoy = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonEstadisticas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButtonCerrarSesion = new javax.swing.JButton();
        jButtonAyuda = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));
        jPanel1.setForeground(new java.awt.Color(18, 18, 18));

        jLabelNombre.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Perfil");

        jButtonFoto.setBackground(new java.awt.Color(18, 18, 18));
        jButtonFoto.setBorderPainted(false);
        jButtonFoto.setContentAreaFilled(false);
        jButtonFoto.setFocusable(false);
        jButtonFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFotoActionPerformed(evt);
            }
        });

        jLabelSegundoApellido.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSegundoApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSegundoApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelPrimerApellido.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPrimerApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrimerApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 128, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPrimerApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSegundoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 300));

        jPanel2.setBackground(new java.awt.Color(18, 18, 18));
        jPanel2.setForeground(new java.awt.Color(18, 18, 18));

        jButtonFactura.setBackground(new java.awt.Color(51, 51, 51));
        jButtonFactura.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButtonFactura.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFactura.setText("Factura");
        jButtonFactura.setBorderPainted(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Boleta  Compra");

        jTextAreaFactura.setEditable(false);
        jTextAreaFactura.setBackground(new java.awt.Color(102, 102, 102));
        jTextAreaFactura.setColumns(20);
        jTextAreaFactura.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextAreaFactura.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaFactura.setRows(5);
        jTextAreaFactura.setCaretColor(new java.awt.Color(102, 102, 102));
        jTextAreaFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextAreaFactura.setEnabled(false);
        jTextAreaFactura.setFocusable(false);
        jTextAreaFactura.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTextAreaFactura);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonFactura)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1374, 30, 230, 620));

        jPanel3.setBackground(new java.awt.Color(18, 18, 18));
        jPanel3.setForeground(new java.awt.Color(18, 18, 18));

        jButtonAgregar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAgregar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setText("Agregar Producto");
        jButtonAgregar.setBorderPainted(false);

        jButtonModifica.setBackground(new java.awt.Color(51, 51, 51));
        jButtonModifica.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButtonModifica.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModifica.setText("Modificar Producto");
        jButtonModifica.setBorderPainted(false);
        jButtonModifica.setVerifyInputWhenFocusTarget(false);

        jButtonEliminar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonEliminar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar Producto");
        jButtonEliminar.setBorderPainted(false);
        jButtonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEliminarMouseExited(evt);
            }
        });
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jLabeTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabeTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabeTitulo.setText("Panel de Control");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabeTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButtonAgregar)
                .addGap(18, 18, 18)
                .addComponent(jButtonModifica)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminar)
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1374, 670, 230, 210));

        jPanel4.setBackground(new java.awt.Color(18, 18, 18));
        jPanel4.setForeground(new java.awt.Color(18, 18, 18));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Destacados");

        jButtonVentaHoy.setBackground(new java.awt.Color(18, 18, 18));
        jButtonVentaHoy.setBorderPainted(false);
        jButtonVentaHoy.setContentAreaFilled(false);
        jButtonVentaHoy.setFocusable(false);
        jButtonVentaHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVentaHoyActionPerformed(evt);
            }
        });

        jButtonGananciaHoy.setBackground(new java.awt.Color(18, 18, 18));
        jButtonGananciaHoy.setBorderPainted(false);
        jButtonGananciaHoy.setContentAreaFilled(false);
        jButtonGananciaHoy.setFocusable(false);
        jButtonGananciaHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGananciaHoyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
            .addComponent(jButtonGananciaHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonVentaHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jButtonGananciaHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonVentaHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 190, 500));

        jPanel5.setBackground(new java.awt.Color(18, 18, 18));
        jPanel5.setForeground(new java.awt.Color(18, 18, 18));

        jTable1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CANTIDAD", "MARCA", "PRECIO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jScrollPane1.setViewportView(jTable1);

        jButtonEstadisticas.setBackground(new java.awt.Color(51, 51, 51));
        jButtonEstadisticas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEstadisticas.setText("Estadísticas");
        jButtonEstadisticas.setBorderPainted(false);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tabla de Productos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1138, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jButtonEstadisticas))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEstadisticas)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 580, -1, 300));

        jPanel6.setBackground(new java.awt.Color(18, 18, 18));
        jPanel6.setForeground(new java.awt.Color(18, 18, 18));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1162, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 30, 1162, 530));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCerrarSesion.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCerrarSesion.setText("Cerrar Sesión");
        jButtonCerrarSesion.setBorderPainted(false);
        jButtonCerrarSesion.setFocusable(false);
        jButtonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCerrarSesionMouseExited(evt);
            }
        });
        jPanel7.add(jButtonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 0, 150, 30));

        jButtonAyuda.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAyuda.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAyuda.setText("?");
        jButtonAyuda.setBorderPainted(false);
        jButtonAyuda.setFocusable(false);
        jButtonAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAyudaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAyudaMouseExited(evt);
            }
        });
        jPanel7.add(jButtonAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 0, -1, 30));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 30));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1594, 30));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setPreferredSize(new java.awt.Dimension(1607, 850));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1610, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarMouseEntered
        jButtonEliminar.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_jButtonEliminarMouseEntered

    private void jButtonEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarMouseExited
        jButtonEliminar.setBackground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_jButtonEliminarMouseExited

    private void jButtonCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionMouseEntered
        jButtonCerrarSesion.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButtonCerrarSesionMouseEntered

    private void jButtonCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionMouseExited
        jButtonCerrarSesion.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jButtonCerrarSesionMouseExited

    private void jButtonAyudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAyudaMouseEntered
        jButtonAyuda.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButtonAyudaMouseEntered

    private void jButtonAyudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAyudaMouseExited
        jButtonAyuda.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jButtonAyudaMouseExited

    private void jButtonFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFotoActionPerformed
        
    }//GEN-LAST:event_jButtonFotoActionPerformed

    private void jButtonVentaHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVentaHoyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVentaHoyActionPerformed

    private void jButtonGananciaHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGananciaHoyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGananciaHoyActionPerformed
    public  void addPropiedades(JButton boton)
    {
        
        boton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        boton.setContentAreaFilled(false);
        boton.setFocusable(false);
        
        boton.setBackground(new Color(18,18,18));
        boton.setBorderPainted(false);
        
        
    }
    /**
     * @param args the command line arguments
     */
    
    public JButton mayorGanancia = new EfectoHoverBoton();
    public JButton menorGanancia = new EfectoHoverBoton();
    public JButton mayorVenta = new EfectoHoverBoton();
    public JButton menorVenta = new EfectoHoverBoton();
    
    public JButton gananciaHoy = new EfectoHoverBoton();
    public JButton ventaHoy = new EfectoHoverBoton();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAgregar;
    public javax.swing.JButton jButtonAyuda;
    public javax.swing.JButton jButtonCerrarSesion;
    public javax.swing.JButton jButtonEliminar;
    public javax.swing.JButton jButtonEstadisticas;
    public javax.swing.JButton jButtonFactura;
    public javax.swing.JButton jButtonFoto;
    public javax.swing.JButton jButtonGananciaHoy;
    public javax.swing.JButton jButtonModifica;
    public javax.swing.JButton jButtonVentaHoy;
    private javax.swing.JLabel jLabeTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabelNombre;
    public javax.swing.JLabel jLabelPrimerApellido;
    public javax.swing.JLabel jLabelSegundoApellido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextArea jTextAreaFactura;
    // End of variables declaration//GEN-END:variables
}
