/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Luis Huayta
 */
public class VistaPerfil extends javax.swing.JDialog {

    /**
     * Creates new form VistaPerfil
     */
    public VistaPerfil(JFrame frame,boolean modal) {
        super(frame,modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonRegresar = new javax.swing.JButton();
        jLabelBarra = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldCuenta = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidoPaterno = new javax.swing.JTextField();
        jTextFieldApellidoMaterno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonCuenta = new javax.swing.JButton();
        jButtonNombre = new javax.swing.JButton();
        jButtonApellidoPaterno = new javax.swing.JButton();
        jButtonApellidoMaterno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegresar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRegresar.setBorderPainted(false);
        jButtonRegresar.setFocusable(false);
        jButtonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRegresarMouseExited(evt);
            }
        });
        jPanel1.add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 100, 22));

        jLabelBarra.setBackground(new java.awt.Color(0, 0, 0));
        jLabelBarra.setOpaque(true);
        jPanel1.add(jLabelBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 20));

        jPanel2.setBackground(new java.awt.Color(18, 18, 18));

        jTextFieldCuenta.setEditable(false);
        jTextFieldCuenta.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldCuenta.setOpaque(true);
        jTextFieldCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCuentaActionPerformed(evt);
            }
        });

        jTextFieldNombre.setEditable(false);
        jTextFieldNombre.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldNombre.setOpaque(true);

        jTextFieldApellidoPaterno.setEditable(false);
        jTextFieldApellidoPaterno.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldApellidoPaterno.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldApellidoPaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldApellidoPaterno.setOpaque(true);
        jTextFieldApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoPaternoActionPerformed(evt);
            }
        });

        jTextFieldApellidoMaterno.setEditable(false);
        jTextFieldApellidoMaterno.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldApellidoMaterno.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldApellidoMaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldApellidoMaterno.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Perfil");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cuenta");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido Paterno");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellido Materno");

        jButtonCuenta.setBackground(new java.awt.Color(51, 51, 51));
        jButtonCuenta.setBorderPainted(false);
        jButtonCuenta.setFocusable(false);
        jButtonCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCuentaMouseExited(evt);
            }
        });

        jButtonNombre.setBackground(new java.awt.Color(51, 51, 51));
        jButtonNombre.setBorderPainted(false);
        jButtonNombre.setFocusable(false);
        jButtonNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonNombreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonNombreMouseExited(evt);
            }
        });

        jButtonApellidoPaterno.setBackground(new java.awt.Color(51, 51, 51));
        jButtonApellidoPaterno.setBorderPainted(false);
        jButtonApellidoPaterno.setFocusable(false);
        jButtonApellidoPaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonApellidoPaternoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonApellidoPaternoMouseExited(evt);
            }
        });

        jButtonApellidoMaterno.setBackground(new java.awt.Color(51, 51, 51));
        jButtonApellidoMaterno.setBorderPainted(false);
        jButtonApellidoMaterno.setFocusable(false);
        jButtonApellidoMaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonApellidoMaternoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonApellidoMaternoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldApellidoPaterno)
                                    .addComponent(jTextFieldApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonApellidoMaterno)
                                    .addComponent(jButtonApellidoPaterno)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldCuenta)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCuenta)
                                    .addComponent(jButtonNombre))))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButtonNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButtonApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButtonApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarMouseEntered
        // TODO add your handling code here:
         jButtonRegresar.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButtonRegresarMouseEntered

    private void jButtonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarMouseExited
        jButtonRegresar.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jButtonRegresarMouseExited

    private void jTextFieldCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCuentaActionPerformed

    private void jTextFieldApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoPaternoActionPerformed

    private void jButtonCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCuentaMouseEntered
        // TODO add your handling code here:
        jButtonCuenta.setBackground(new java.awt.Color(0,102,255));
    }//GEN-LAST:event_jButtonCuentaMouseEntered

    private void jButtonCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCuentaMouseExited
        // TODO add your handling code here:
        
        jButtonCuenta.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButtonCuentaMouseExited

    private void jButtonNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNombreMouseEntered
        // TODO add your handling code here:
        jButtonNombre.setBackground(new java.awt.Color(0,102,255));
    }//GEN-LAST:event_jButtonNombreMouseEntered

    private void jButtonNombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNombreMouseExited
        // TODO add your handling code here:
        
        jButtonNombre.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButtonNombreMouseExited

    private void jButtonApellidoPaternoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonApellidoPaternoMouseEntered
        // TODO add your handling code here:
        
        jButtonApellidoPaterno.setBackground(new java.awt.Color(0,102,255));
    }//GEN-LAST:event_jButtonApellidoPaternoMouseEntered

    private void jButtonApellidoPaternoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonApellidoPaternoMouseExited
        // TODO add your handling code here:
        jButtonApellidoPaterno.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButtonApellidoPaternoMouseExited

    private void jButtonApellidoMaternoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonApellidoMaternoMouseEntered
        // TODO add your handling code here:
        
        jButtonApellidoMaterno.setBackground(new java.awt.Color(0,102,255));
    }//GEN-LAST:event_jButtonApellidoMaternoMouseEntered

    private void jButtonApellidoMaternoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonApellidoMaternoMouseExited
        // TODO add your handling code here:
        jButtonApellidoMaterno.setBackground(new Color(51,51,51));
        
    }//GEN-LAST:event_jButtonApellidoMaternoMouseExited

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonApellidoMaterno;
    public javax.swing.JButton jButtonApellidoPaterno;
    public javax.swing.JButton jButtonCuenta;
    public javax.swing.JButton jButtonNombre;
    public javax.swing.JButton jButtonRegresar;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabelBarra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jTextFieldApellidoMaterno;
    public javax.swing.JTextField jTextFieldApellidoPaterno;
    public javax.swing.JTextField jTextFieldCuenta;
    public javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
