/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.EfectoHoverBoton;
import Modelo.EfectoHoverLabel;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Luis Huayta
 */
public class VistaVentas extends javax.swing.JDialog {

    /**
     * Creates new form vistaVentas
     */
    
 
    public VistaVentas(JFrame parent, boolean modal) {
        super(parent,modal);
        initComponents();
        setLocationRelativeTo(null);
        estadisticaProducto.setBounds(230, 80, 210, 210);
        estadisticaEmpresa.setBounds(450, 80, 210, 210);
        estadisticaFactura.setBounds(10, 80, 210, 210);
        labelEmpresa.setBounds(491, 50,120,30);
        labelFactura.setBounds(52, 50,120,30);
        labelProducto.setBounds(280, 50,120,30);
        
        addPropiedadesLabel(labelEmpresa);
        addPropiedadesLabel(labelFactura);
        addPropiedadesLabel(labelProducto);
        
        addPropiedadesBoton(estadisticaProducto);
        addPropiedadesBoton(estadisticaEmpresa);
        addPropiedadesBoton(estadisticaFactura);
        
        jPanelFondo.add(estadisticaProducto);
        jPanelFondo.add(estadisticaEmpresa);
        jPanelFondo.add(estadisticaFactura);
        jPanelFondo.add(labelEmpresa);
        jPanelFondo.add(labelFactura);
        jPanelFondo.add(labelProducto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabelBarra = new javax.swing.JLabel();
        jPanelFondo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setToolTipText("");
        jButton1.setBorderPainted(false);
        jButton1.setFocusable(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 140, 20));
        jPanel3.add(jLabelBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 20));

        jPanelFondo.setBackground(new java.awt.Color(18, 18, 18));

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 670, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
    public  void addPropiedadesBoton(JButton boton)
    {
        
        boton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        boton.setContentAreaFilled(false);
        boton.setFocusable(false);
       
        boton.setBackground(new Color(18,18,18));
        boton.setBorderPainted(false);
        
        
    }
    public void addPropiedadesLabel(JLabel label)
    {
        label.setOpaque(false);
        label.setForeground(new Color(255,255,255));
        
        label.setFocusable(false);
        label.setHorizontalAlignment(JLabel.CENTER);
        label.setVerticalAlignment(JLabel.CENTER);
        label.setFont(new Font("Estandar",Font.BOLD,15));
    }
    public JButton estadisticaProducto = new EfectoHoverBoton();
    public JButton estadisticaEmpresa = new EfectoHoverBoton();
    public JButton estadisticaFactura = new EfectoHoverBoton();
    public JLabel labelProducto = new EfectoHoverLabel("PRODUCTOS");
    public JLabel labelFactura = new EfectoHoverLabel("FACTURAS");
    public JLabel labelEmpresa = new EfectoHoverLabel("EMPRESA");
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabelBarra;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelFondo;
    // End of variables declaration//GEN-END:variables
}
